export const Details = [
    {
        caseNumber: "RRZU9D6BVG",
        firstName: "Oyindamola",
        lastName:"Adebayo",
        applicationDate: "01/04/2023",
        recentUpdate:"04/04/2023",
        loanStatus:"Pending",
    },
    {
        caseNumber: "GR45467RBA",
        firstName: "Temidayo",
        lastName:"Adebayo",
        applicationDate: "01/04/2023",
        recentUpdate:"04/04/2023",
        loanStatus:"Approved",
    },
    {
        caseNumber: "RRZU9D6BVG",
        firstName: "Temidayo",
        lastName:"Adebayo",
        applicationDate: "01/04/2023",
        recentUpdate:"04/04/2023",
        loanStatus:"Due",
    },
    {
        caseNumber: "GR45467RBA",
        firstName: "Temidayo",
        lastName:"Adebayo",
        applicationDate: "01/04/2023",
        recentUpdate:"04/04/2023",
        loanStatus:"Closed",
    },
    {
        caseNumber: "RRZU9D6BVG",
        firstName: "Temidayo",
        lastName:"Adebayo",
        applicationDate: "01/04/2023",
        recentUpdate:"04/04/2023",
        loanStatus:"Approved",
    },
    {
        caseNumber: "GR45467RBA",
        firstName: "Temidayo",
        lastName:"Adebayo",
        applicationDate: "01/04/2023",
        recentUpdate:"04/04/2023",
        loanStatus:"Approved",
    },
    {
        caseNumber: "RRZU9D6BVG",
        firstName: "Temidayo",
        lastName:"Adebayo",
        applicationDate: "01/04/2023",
        recentUpdate:"04/04/2023",
        loanStatus:"Closed",
    },
    {
        caseNumber: "GR45467RBA",
        firstName: "Temidayo",
        lastName:"Adebayo",
        applicationDate: "01/04/2023",
        recentUpdate:"04/04/2023",
        loanStatus:"Declined",
    },
    {
        caseNumber: "RRZU9D6BVG",
        firstName: "Temidayo",
        lastName:"Adebayo",
        applicationDate: "01/04/2023",
        recentUpdate:"04/04/2023",
        loanStatus:"Extended",
    }
];
