const tableData =[
    {
        caseNumber: "RRZU9D6BVG",
        firstName: "Temitayo",
        lastName: "Adedayo",
        applicationDate: "1/05/2023",
        recentUpdate: "05/05/2023",
        loanStatus: "Pending",
    },
    {
        caseNumber: "RRZU9D6BVG",
        firstName: "Temitayo",
        lastName: "Adedayo",
        applicationDate: "1/05/2023",
        recentUpdate: "05/05/2023",
        loanStatus: "Approved",
    },
    {
        caseNumber: "RRZU9D6BVG",
        firstName: "Temitayo",
        lastName: "Adedayo",
        applicationDate: "1/05/2023",
        recentUpdate: "05/05/2023",
        loanStatus: "Approved",
    },
    {
        caseNumber: "RRZU9D6BVG",
        firstName: "Temitayo",
        lastName: "Adedayo",
        applicationDate: "1/05/2023",
        recentUpdate: "05/05/2023",
        loanStatus: "Pending",
    },
    {
        caseNumber: "RRZU9D6BVG",
        firstName: "Temitayo",
        lastName: "Adedayo",
        applicationDate: "1/05/2023",
        recentUpdate: "05/05/2023",
        loanStatus: "Pending",
    },
    {
        caseNumber: "RRZU9D6BVG",
        firstName: "Temitayo",
        lastName: "Adedayo",
        applicationDate: "1/05/2023",
        recentUpdate: "05/05/2023",
        loanStatus: "Approved",
    },
    {
        caseNumber: "RRZU9D6BVG",
        firstName: "Temitayo",
        lastName: "Adedayo",
        applicationDate: "1/05/2023",
        recentUpdate: "05/05/2023",
        loanStatus: "Pending",
    },
    {
        caseNumber: "RRZU9D6BVG",
        firstName: "Temitayo",
        lastName: "Adedayo",
        applicationDate: "1/05/2023",
        recentUpdate: "05/05/2023",
        loanStatus: "Approved",
    },
    {
        caseNumber: "RRZU9D6BVG",
        firstName: "Temitayo",
        lastName: "Adedayo",
        applicationDate: "1/05/2023",
        recentUpdate: "05/05/2023",
        loanStatus: "Pending",
    }
]
export default tableData;